<?php

$pol_arr = array(
	'Lars Løkke Rasmussen', 
	'Helle Thorning Schmidt',
	'Kristian Thuelsen Dahl',
	'Anders Samuelsen',
	'Bertel Haarder',
	'Bjarne Corydon',
	'Brian Mikkelsen',
	'Christine Antorini',
	'Claus Hjort Frederiksen',
	'Dan Jørgensen',
	'Frank Aaen',
	'Holger K. Nielsen',
	'Ida Auken',
	'Inger Støjberg',
	'Joachim B. Olsen',
	'Karen Ellemann',
	'Johanne Schmidt Nielsen',
	'Kristian Jensen',
	'Magnus Heunicke',
	'Marianne Jelved',
	'Martin Henriksen',
	'Mette Frederiksen',
	'Mogens Lykketoft',
	'Søren Gade',
	'Zenia Stampe',
	'Morten Østergaard',
	'Naser Khader',
	'Pernille Skipper',
	'Pia Kjærsgaard',
	'Simon Emil Ammitzbøll',
	'Søren Pind',
	'Søren Espersen',
	'Uffe Elbæk'
);

$pol_first = array(
	'Lars', 
	'Helle',
	'Kristian',
	'Anders',
	'Bertel',
	'Bjarne',
	'Brian',
	'Christine',
	'Claus',
	'Dan',
	'Frank',
	'Holger',
	'Ida',
	'Inger',
	'Joachim',
	'Karen',
	'Johanne',
	'Kristian',
	'Magnus',
	'Marianne',
	'Martin',
	'Mette',
	'Mogens',
	'Søren',
	'Zenia',
	'Morten',
	'Naser',
	'Pernille',
	'Pia',
	'Simon Emil',
	'Søren',
	'Søren',
	'Uffe'
);

$pol_last = array(
	'Løkke',
	'Rasmussen', 
	'Thorning',
	'Schmidt',
	'Thuelsen',
	'Dahl',
	'Samuelsen',
	'Haarder',
	'Corydon',
	'Mikkelsen',
	'Antorini',
	'Hjort',
	'Frederiksen',
	'Jørgensen',
	'Aaen',
	'K.',
	'Nielsen',
	'Auken',
	'Støjberg',
	'B.',
	'Olsen',
	'Ellemann',
	'Schmidt',
	'Nielsen',
	'Jensen',
	'Heunicke',
	'Jelved',
	'Henriksen',
	'Frederiksen',
	'Lykketoft',
	'Gade',
	'Stampe',
	'Østergaard',
	'Khader',
	'Skipper',
	'Kjærsgaard',
	'Ammitzbøll',
	'Pind',
	'Espersen',
	'Elbæk'
);

$pol_citat = array(
	'Mere service',
	'Mindre bureaukrati',
	'Flere arbejdspladser',
	'Markedet er ved at vende',
	'Pas på miljøet før det er for sent',
	'Danmark er et af de tryggeste samfund i verden'
);

$replace = array('.',' ','æ','ø','å','Ø');
$with = array('','','ae','oe','aa','oe');

?>
